### ISSUE TITLE
Remover config Firebase

### ISSUE THREAD

**Issue by romulosous** [ifpi-picos/projeto-integrador-i-class-schedule-frontend#54]
- [ ] Remover todas as integrações que houver com o firebase, exeto deploy, pois isso ainda sera migrado para outro serviço de hospedagem

**Comment by MichelFonseca1024** [comment]
Remover tadas as integrações que houver com o firebase, exeto deploy, pois isso ainda sera migrado para outro serviço de hospedagem

**Comment by MichelFonseca1024** [comment]
verifica se o .env.local é necessario para deploy, se não pode remover
